import "./globals.css"
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "./Components/Footer/page"
import Header from "./Components/Header/page"
import StoreInitializer from "./StoreInitializer/storeinitializer";
import data from "../store/state.json"
import {useStore} from "../src/store"





const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  useStore.setState({
    layout: data.layout,
    saturatedPlayfield: data.saturatedPlayfield,
    order: data.order,
  
  })
  /* const saturatePlayfield = (rows: number, cols: number, val: number) => {
    let res = [];
    for (let i = 0; i < rows; i++) {
        res.push(new Array(cols).fill(val));
    }
    useStore.getState().setSaturatedPlayfield(res); // Use the action to update the state
  }; */
  

  return (
    <html lang="en">
      <body className="container">
        <StoreInitializer layout={data.layout} order={data.order} saturatedPlayfield={data.saturatedPlayfield} />
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}