import "./globals.css"
import type { Metadata } from "next";
import { Lato } from "next/font/google";
import "./globals.css";
import Footer from "./Components/Footer/page"
import Header from "./Components/Header/page"
import StoreInitializer from "./StoreInitializer/storeinitializer";
import {useStore} from "../src/store"
import {Store} from "../interfaceList"






const lato = Lato({ 
  weight: ['400', '700'],
  style: 'normal',
  subsets: ["latin"] 
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {



  const axios = require('axios')

  


  async function  fetchData ()  {
    
    try{
      const response = await axios.get("https://raw.githubusercontent.com/Blnkfc/TicTacToeButCooler/main/data/state.json")
      return response.data
    }
    catch(error){
      console.error(error)
      throw(error)
    }
  }

  async function getData(){
    return await fetchData()
  }

  const data:Store = await getData()
  

  useStore.setState({
    layout: data.layout,
    saturatedPlayfield: data.saturatedPlayfield,
    order: data.order,
    skinSet: data.skinSet,
    directionArray: data.directionArray,
    lastChangedCell: data.lastChangedCell,
    win: data.win
  })
 
  

  return (
    <html lang="en">
      <body className="container">
        <StoreInitializer 
        layout={data.layout} order={data.order} saturatedPlayfield={data.saturatedPlayfield} 
        skinSet={data.skinSet} directionArray={data.directionArray} lastChangedCell={data.lastChangedCell} win={data.win} />
        <Header />
        <main className={lato.className} >{children}</main>
        <Footer />
      </body>
    </html>
  );
}